#!/usr/bin/env python3

import sys
import subprocess

if __name__ == '__main__':
    if len(sys.argv) < 2:
        exit(-1)

    executable = sys.argv[1]

    output = ''
    try:
        output = subprocess.check_output(['valgrind', '--tool=memcheck', '--leak-check=yes', executable], stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError as e:
        print(e.output)
        exit(-1)

    if 'All heap blocks were freed' in output.decode():
        exit(0)
    else:
        print(output.decode())
        exit(-1)
